#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '{
    "apollo_server":"https://mummyscake-backend.onrender.com/graphql"
}' >> src/environment.josn

git add src/environment.json

# npx lint-staged

echo "Working"